JRA-134 Added test for route editor

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,7 +1,18 @@
 #!/bin/sh
 echo "*****Running unit tests & lint******"
-./gradlew test
 ./gradlew lintKotlin
 status=$?
+CMD="./gradlew clean test"
+# Check if we actually have commits to push
+commits=`git log @{u}..`
+if [ -z "$commits" ]; then
+ exit 0
+fi
+$CMD
+RESULT=$?
+if [ $RESULT -ne 0 ]; then
+ echo "failed $CMD"
+ exit 1
+fi
 echo "*****Done with unit tests & lint******"
 exit $status
